import assert from 'node:assert/strict';
import { calculateAtmosphere, temperatureToC, calculateFlightSpeeds, calculateClimbPlan, calculateDescentPlan } from '../src/performance-calculations.js';
const atmosphere=calculateAtmosphere({fieldElevationFt:5000,temperatureC:25,altimeterInHg:29.92});
assert.equal(atmosphere.pressureAltitudeFt,5000);assert.ok(atmosphere.densityAltitudeFt>5000);assert.equal(calculateAtmosphere({fieldElevationFt:5000,temperatureC:25,altimeterInHg:40}),null);
assert.equal(temperatureToC(68,'f'),20);assert.equal(temperatureToC(20,'c'),20);assert.equal(temperatureToC(200,'f'),null);
const calm=calculateFlightSpeeds({indicatedAirspeedKt:73,averageAltitudeFt:6500,temperatureC:20,noWind:true});assert.ok(calm.estimatedTasKt>73);assert.equal(calm.estimatedGroundspeedKt,calm.estimatedTasKt);
const headwind=calculateFlightSpeeds({indicatedAirspeedKt:73,averageAltitudeFt:6500,temperatureC:20,noWind:false,courseDeg:180,windDirectionDeg:180,windSpeedKt:10});assert.ok(headwind.estimatedGroundspeedKt<calm.estimatedGroundspeedKt);
const toc=calculateClimbPlan({startAltitudeFt:5000,targetAltitudeFt:8000,verticalSpeedFpm:500,groundspeedKt:73});assert.equal(toc.climbMinutes,6);assert.equal(toc.approximateDistanceNm,7.3);
const tod=calculateDescentPlan({cruiseAltitudeFt:10000,targetAltitudeFt:5000,descentRateFpm:500,groundspeedKt:90});assert.equal(tod.descentMinutes,10);assert.equal(tod.distanceNm,15);
console.log('Flight Math calculations passed.');
