import { ac } from './aircraft.js';
import { airportCodes, airportRecord } from './airports.js';
import { getWbSnapshot } from './wb.js';
import { datasetForAircraft, datasetReady } from './performance-datasets.js';
import { calculateAtmosphere, calculateWindComponent } from './performance-calculations.js';

var ctx=null;
function e(id){return ctx.el(id)}
function text(id,value){var node=e(id);if(node)node.textContent=value==null||value===''?'—':String(value)}
function number(id){var value=e(id).value.trim();return value===''?null:Number(value)}
function savedPlan(){try{return JSON.parse(localStorage.jp_routePlan||'null')||{}}catch(error){return {}}}
function parseRunway(raw){var value=String(raw||''),ident=((value.match(/^([^•]+)/)||[])[1]||'').trim(),length=((value.match(/([\d,]+)\s*ft/i)||[])[1]||'').replace(/,/g,''),surfaceMatch=value.match(/\b(ASPHALT|ASPH|ASP|CONCRETE|CONC|CON|TURF|GRASS|GRAVEL|DIRT)\b/i),slopeMatch=value.match(/slope\s*[:=]?\s*(-?[\d.]+)\s*%/i),ends=ident.split('/').map(function(end){return end.trim()}).filter(Boolean);if(!ends.length)ends=[ident||'Runway'];return {raw:value,ident:ident,lengthFt:length?Number(length):null,surface:surfaceMatch?surfaceMatch[1].toUpperCase():null,slopePercent:slopeMatch?Number(slopeMatch[1]):null,ends:ends}}
function runwayHeading(end){var match=String(end||'').match(/^(\d{1,2})/),value=match?Number(match[1]):null;return value==null?null:(value===36?360:value*10)}
function populateAirports(){var select=e('perfAirport'),prior=select.value||localStorage.jp_perfAirport||savedPlan().departure||'';select.innerHTML='';var blank=document.createElement('option');blank.value='';blank.textContent='Select saved airport';select.appendChild(blank);airportCodes().forEach(function(code){var option=document.createElement('option');option.value=code;option.textContent=code+' — '+((airportRecord(code)||{}).name||'Airport');select.appendChild(option)});select.value=airportCodes().indexOf(prior)>=0?prior:''}
function populateRunways(){var airport=airportRecord(e('perfAirport').value),select=e('perfRunway'),prior=localStorage.jp_perfRunway||'';select.innerHTML='';var blank=document.createElement('option');blank.value='';blank.textContent='Select runway end';select.appendChild(blank);((airport&&airport.runways)||[]).forEach(function(raw,index){var runway=parseRunway(raw);runway.ends.forEach(function(end,endIndex){var option=document.createElement('option');option.value=index+':'+endIndex;option.textContent='Runway '+end+(runway.lengthFt?' — '+runway.lengthFt+' ft':'');select.appendChild(option)})});if(Array.from(select.options).some(function(option){return option.value===prior}))select.value=prior;render()}
function selectedRunway(){var airport=airportRecord(e('perfAirport').value),parts=e('perfRunway').value.split(':'),index=Number(parts[0]),endIndex=Number(parts[1]);if(!airport||e('perfRunway').value===''||!airport.runways[index])return null;var runway=parseRunway(airport.runways[index]);runway.end=runway.ends[endIndex]||runway.ends[0];runway.heading=runwayHeading(runway.end);return runway}
function populateFlaps(dataset){var select=e('perfFlaps'),ready=datasetReady(dataset),prior=select.value;select.innerHTML='';var blank=document.createElement('option');blank.value='';blank.textContent=ready?'Select verified POH flap setting':'No verified POH performance data.';select.appendChild(blank);if(ready){Array.from(new Set((dataset.configurations||[]).reduce(function(values,item){return values.concat([item.flapSetting,item.takeoffFlapSetting,item.landingFlapSetting],item.takeoffFlapSettings||[],item.landingFlapSettings||[])},[]).map(function(value){return String(value||'').trim()}).filter(Boolean))).forEach(function(value){var option=document.createElement('option');option.value=value;option.textContent=value;select.appendChild(option)})}select.disabled=!ready;if(ready&&Array.from(select.options).some(function(option){return option.value===prior}))select.value=prior}
function lockDistances(message){['perfGroundRoll','perfObstacleDistance','perfRunwayRemaining','perfMarginResult'].forEach(function(id){text(id,'LOCKED')});text('perfResultMessage',message)}
function render(){if(!ctx)return;var aircraft=ac()||{},wb=getWbSnapshot(),dataset=datasetForAircraft(aircraft),ready=datasetReady(dataset),airport=airportRecord(e('perfAirport').value),runway=selectedRunway();text('perfRegistration',aircraft.n||'Missing');text('perfAircraftModel',aircraft.type||'Missing');text('perfAircraftWeight',wb&&Number.isFinite(wb.totalWeightLb)?wb.totalWeightLb.toFixed(1)+' lb':'Not available from current W&B');e('perfDatasetStatus').textContent=ready?'Verified built-in POH data available':'No verified POH performance data.';e('perfDatasetStatus').className='pill '+(ready?'good':'bad');populateFlaps(dataset);text('perfElevation',airport&&airport.elevation!==''?airport.elevation+' ft':'Not available');text('perfRunwayLength',runway&&runway.lengthFt?runway.lengthFt+' ft':'Not available');text('perfRunwayHeading',runway&&runway.heading!=null?String(runway.heading).padStart(3,'0')+'°':'Not available');text('perfRunwaySurface',runway&&runway.surface?runway.surface:'Not available in airport database');text('perfRunwaySlope',runway&&runway.slopePercent!=null?runway.slopePercent.toFixed(1)+'%':'Not available in airport database');var elevation=airport?Number(airport.elevation):null,atmosphere=calculateAtmosphere({fieldElevationFt:elevation,temperatureC:number('perfTemperature'),altimeterInHg:number('perfAltimeter')});text('perfPressureAltitude',atmosphere?Math.round(atmosphere.pressureAltitudeFt)+' ft':'Enter elevation, temperature and altimeter');text('perfDensityAltitude',atmosphere?Math.round(atmosphere.densityAltitudeFt)+' ft':'Enter elevation, temperature and altimeter');var component=runway&&runway.heading!=null?calculateWindComponent({runwayHeadingDeg:runway.heading,windDirectionDeg:number('perfWindDirection'),windSpeedKt:number('perfWindSpeed')}):null;text('perfWindComponent',component?(Math.abs(component.componentKt).toFixed(1)+' kt '+(component.componentKt>=0?'headwind':'tailwind')):'Enter runway and wind');localStorage.jp_perfAirport=e('perfAirport').value;localStorage.jp_perfRunway=e('perfRunway').value;if(!ready)return lockDistances('No verified POH performance data. Atmospheric and wind values are shown, but aircraft distances are not estimated.');if(e('perfModifications').value!=='no')return lockDistances('Aircraft modifications must be confirmed “No” before built-in POH data can apply.');lockDistances('No distance is shown unless every condition exactly matches approved structured POH data. No extrapolation or estimation is permitted.')}
export function renderPerformance(){if(!ctx)return;populateAirports();populateRunways();render()}
export function initPerformance(context){ctx=context;populateAirports();populateRunways();e('perfAirport').addEventListener('change',populateRunways);e('perfRunway').addEventListener('change',render);['perfModifications','perfOperation','perfTemperature','perfAltimeter','perfWindDirection','perfWindSpeed','perfRunwayCondition','perfFlaps','perfTechnique','perfSafetyMargin'].forEach(function(id){e(id).addEventListener('input',render);e(id).addEventListener('change',render)});render()}
