import { airportCodes, airportRecord } from './airports.js';
import { calculateAtmosphere, temperatureToC, calculateFlightSpeeds, calculateClimbPlan, calculateDescentPlan } from './performance-calculations.js';

var ctx=null,attempted={density:false,toc:false,tod:false},units={density:'c',toc:'c',tod:'c'};
function e(id){return ctx.el(id)}
function value(id){var node=e(id),raw=node?node.value.trim():'';return raw===''?null:Number(raw)}
function set(id,val){if(e(id))e(id).textContent=val==null?'—':String(val)}
function save(id){localStorage['jp_'+id]=e(id).value}
function clearIds(ids){ids.forEach(function(id){e(id).value='';localStorage.removeItem('jp_'+id)})}
function validTemperature(id,unit){return temperatureToC(value(id),unit)}
function normalizeAltimeter(){var node=e('mathAltimeter'),raw=Number(node.value);if(Number.isInteger(raw)&&raw>=2500&&raw<=3500){node.value=(raw/100).toFixed(2);save('mathAltimeter')}}
function updateUnitInput(tool){var id=tool==='density'?'mathTemperature':tool==='toc'?'mathTocTemperature':'mathTodTemperature',unit=units[tool],node=e(id);node.min=unit==='f'?'-148':'-100';node.max=unit==='f'?'158':'70'}
function switchUnit(tool,next){var id=tool==='density'?'mathTemperature':tool==='toc'?'mathTocTemperature':'mathTodTemperature',node=e(id),old=units[tool],n=Number(node.value);if(node.value!==''&&Number.isFinite(n)&&old!==next)node.value=(next==='f'?n*9/5+32:(n-32)*5/9).toFixed(1).replace(/\.0$/,'');units[tool]=next;localStorage['jp_math'+tool+'TempUnit']=next;save(id);updateUnitInput(tool);if(attempted[tool])calculate(tool)}
function showTool(tool){if(['density','toc','tod'].indexOf(tool)<0)tool='density';localStorage.jp_flightMathTool=tool;['density','toc','tod'].forEach(function(name){e('mathTool'+name[0].toUpperCase()+name.slice(1)).classList.toggle('hidden',name!==tool);var button=document.querySelector('[data-math-tool="'+name+'"]');button.classList.toggle('active',name===tool);button.setAttribute('aria-selected',name===tool?'true':'false');button.tabIndex=name===tool?0:-1})}
function populateAirports(){var select=e('mathAirport'),prior=localStorage.jp_mathAirport||'';select.innerHTML='<option value="">Manual entry</option>';airportCodes().forEach(function(code){var airport=airportRecord(code)||{},option=document.createElement('option');option.value=code;option.textContent=code+' — '+(airport.name||'Airport');select.appendChild(option)});if(Array.from(select.options).some(function(o){return o.value===prior}))select.value=prior}
function status(id,message,bad){e(id).textContent=message||'';e(id).style.color=bad?'var(--r)':'var(--m)'}
function calculateDensity(){normalizeAltimeter();var tempC=validTemperature('mathTemperature',units.density),result=calculateAtmosphere({fieldElevationFt:value('mathElevation'),temperatureC:tempC,altimeterInHg:value('mathAltimeter')});e('mathDensityResults').classList.toggle('hidden',!result);if(!result){status('mathAtmosphereStatus','Enter valid elevation, temperature ('+(units.density==='f'?'-148–158 °F':'-100–70 °C')+'), and altimeter (25.00–35.00 inHg).',true);e('mathDensityBreakdown').textContent='';return}status('mathAtmosphereStatus','',false);set('mathPressureAltitude',Math.round(result.pressureAltitudeFt).toLocaleString()+' ft');set('mathDensityAltitude',Math.round(result.densityAltitudeFt).toLocaleString()+' ft');e('mathDensityBreakdown').textContent='Breakdown: pressure altitude = field elevation + altimeter correction; density altitude uses pressure altitude, ISA temperature, and entered OAT.'}
function windValues(prefix){var mode=e(prefix+'WindMode').value;return {noWind:mode==='none',windDirectionDeg:value(prefix+'WindDirection'),windSpeedKt:value(prefix+'WindSpeed')}}
function calculateToc(){var start=value('mathClimbStartAltitude'),target=value('mathClimbTargetAltitude'),tempC=validTemperature('mathTocTemperature',units.toc),wind=windValues('mathToc'),speeds=calculateFlightSpeeds(Object.assign({indicatedAirspeedKt:value('mathClimbGroundspeed'),averageAltitudeFt:start!=null&&target!=null?(start+target)/2:null,temperatureC:tempC,altimeterInHg:value('mathAltimeter')||29.92,courseDeg:value('mathClimbCourse')},wind)),plan=calculateClimbPlan({startAltitudeFt:start,targetAltitudeFt:target,verticalSpeedFpm:value('mathClimbRate'),groundspeedKt:speeds?speeds.estimatedGroundspeedKt:null}),ok=speeds&&plan;e('mathTocResults').classList.toggle('hidden',!ok);if(!ok){status('mathClimbStatus','Enter valid KIAS, climb rate, increasing altitudes, course, temperature, and forecast wind when selected.',true);e('mathTocBreakdown').textContent='';return}status('mathClimbStatus','',false);set('mathTocTas',speeds.estimatedTasKt.toFixed(1)+' kt');set('mathTocGroundspeed',speeds.estimatedGroundspeedKt.toFixed(1)+' kt');set('mathTocTime',plan.climbMinutes.toFixed(1)+' min');set('mathTocDistance',plan.approximateDistanceNm.toFixed(1)+' NM');e('mathTocBreakdown').textContent='Breakdown: altitude gain ÷ climb rate = time; KIAS is adjusted for average altitude and temperature to estimate TAS; along-course wind gives groundspeed; groundspeed × time = distance.'}
function calculateTod(){var cruise=value('mathCruiseAltitude'),target=value('mathTargetAltitude'),tempC=validTemperature('mathTodTemperature',units.tod),wind=windValues('mathTod'),speeds=calculateFlightSpeeds(Object.assign({indicatedAirspeedKt:value('mathDescentGroundspeed'),averageAltitudeFt:cruise!=null&&target!=null?(cruise+target)/2:null,temperatureC:tempC,altimeterInHg:value('mathAltimeter')||29.92,courseDeg:value('mathDescentCourse')},wind)),plan=calculateDescentPlan({cruiseAltitudeFt:cruise,targetAltitudeFt:target,descentRateFpm:value('mathDescentRate'),groundspeedKt:speeds?speeds.estimatedGroundspeedKt:null}),ok=speeds&&plan;e('mathTodResults').classList.toggle('hidden',!ok);if(!ok){status('mathFuelStatus','Enter valid KIAS, descent rate, decreasing altitudes, course, temperature, and forecast wind when selected.',true);e('mathTodBreakdown').textContent='';return}status('mathFuelStatus','',false);set('mathTodTas',speeds.estimatedTasKt.toFixed(1)+' kt');set('mathTodGroundspeed',speeds.estimatedGroundspeedKt.toFixed(1)+' kt');set('mathDescentTime',plan.descentMinutes.toFixed(1)+' min');set('mathDescentDistance',plan.distanceNm.toFixed(1)+' NM');e('mathTodBreakdown').textContent='Breakdown: altitude loss ÷ descent rate = time; KIAS is adjusted for average altitude and temperature to estimate TAS; along-course wind gives groundspeed; groundspeed × time = TOD distance.'}
function calculate(tool){attempted[tool]=true;if(tool==='density')calculateDensity();else if(tool==='toc')calculateToc();else calculateTod()}
function windVisibility(tool){var prefix=tool==='toc'?'mathToc':'mathTod',show=e(prefix+'WindMode').value==='forecast';document.querySelectorAll('.'+(tool==='toc'?'mathTocWind':'mathTodWind')).forEach(function(node){node.classList.toggle('hidden',!show)});localStorage['jp_'+prefix+'WindMode']=e(prefix+'WindMode').value;if(attempted[tool])calculate(tool)}
function reset(tool){var ids=tool==='density'?['mathElevation','mathTemperature','mathAltimeter']:tool==='toc'?['mathClimbGroundspeed','mathClimbRate','mathClimbStartAltitude','mathClimbTargetAltitude','mathClimbCourse','mathTocTemperature','mathTocWindDirection','mathTocWindSpeed']:['mathDescentGroundspeed','mathDescentRate','mathCruiseAltitude','mathTargetAltitude','mathDescentCourse','mathTodTemperature','mathTodWindDirection','mathTodWindSpeed'];clearIds(ids);attempted[tool]=false;var result=tool==='density'?'mathDensityResults':tool==='toc'?'mathTocResults':'mathTodResults',message=tool==='density'?'mathAtmosphereStatus':tool==='toc'?'mathClimbStatus':'mathFuelStatus',breakdown=tool==='density'?'mathDensityBreakdown':tool==='toc'?'mathTocBreakdown':'mathTodBreakdown';e(result).classList.add('hidden');status(message,'',false);e(breakdown).textContent=''}
function example(tool){var values=tool==='density'?{mathElevation:5000,mathTemperature:20,mathAltimeter:29.92}:tool==='toc'?{mathClimbGroundspeed:73,mathClimbRate:500,mathClimbStartAltitude:5000,mathClimbTargetAltitude:8000,mathClimbCourse:180,mathTocTemperature:20}:{mathDescentGroundspeed:90,mathDescentRate:500,mathCruiseAltitude:10000,mathTargetAltitude:5000,mathDescentCourse:180,mathTodTemperature:20};Object.keys(values).forEach(function(id){e(id).value=values[id];save(id)});calculate(tool)}
export function renderPerformance(){if(!ctx)return;showTool(localStorage.jp_flightMathTool||'density');['density','toc','tod'].forEach(function(tool){if(attempted[tool])calculate(tool)})}
export function initPerformance(context){ctx=context;populateAirports();['density','toc','tod'].forEach(function(tool){var savedUnit=localStorage['jp_math'+tool+'TempUnit']||((tool==='toc'||tool==='tod')?localStorage.jp_mathTemperatureUnit:null);units[tool]=savedUnit==='f'?'f':'c';var select=e(tool==='density'?'mathDensityTempUnit':tool==='toc'?'mathTocTempUnit':'mathTodTempUnit');select.value=units[tool];updateUnitInput(tool);select.addEventListener('change',function(){switchUnit(tool,select.value)})});if(e('mathTocTemperature').value===''&&localStorage.jp_mathFlightTemperature)e('mathTocTemperature').value=localStorage.jp_mathFlightTemperature;if(e('mathTodTemperature').value===''&&localStorage.jp_mathFlightTemperature)e('mathTodTemperature').value=localStorage.jp_mathFlightTemperature;document.querySelectorAll('[data-math-tool]').forEach(function(button){button.addEventListener('click',function(){showTool(button.getAttribute('data-math-tool'))})});e('mathAirport').addEventListener('change',function(){localStorage.jp_mathAirport=e('mathAirport').value;var airport=airportRecord(e('mathAirport').value);if(airport&&Number.isFinite(Number(airport.elevation))){e('mathElevation').value=Number(airport.elevation);save('mathElevation')}if(attempted.density)calculateDensity()});e('mathAltimeter').addEventListener('input',normalizeAltimeter);['toc','tod'].forEach(function(tool){var prefix=tool==='toc'?'mathToc':'mathTod';e(prefix+'WindMode').value=localStorage['jp_'+prefix+'WindMode']==='forecast'?'forecast':'none';e(prefix+'WindMode').addEventListener('change',function(){windVisibility(tool)});windVisibility(tool)});[['density','mathDensityCalculate','mathDensityExample','mathDensityReset'],['toc','mathTocCalculate','mathTocExample','mathTocReset'],['tod','mathTodCalculate','mathTodExample','mathTodReset']].forEach(function(item){e(item[1]).addEventListener('click',function(){calculate(item[0])});e(item[2]).addEventListener('click',function(){example(item[0])});e(item[3]).addEventListener('click',function(){reset(item[0])})});showTool(localStorage.jp_flightMathTool||'density')}
