var ctx=null,activeInput=null,lastWbSnapshot=null;
export function getWbSnapshot(){return lastWbSnapshot?Object.assign({},lastWbSnapshot):null}

var rows=[
 {key:'empty',wt:'wbEmptyWt',arm:'wbEmptyArm',moment:'wbEmptyMoment'},
 {key:'pilot',wt:'frontWt',arm:'wbPilotArm',moment:'wbPilotMoment'},
 {key:'frontRight',wt:'wbFrontRightWt',arm:'wbFrontRightArm',moment:'wbFrontRightMoment'},
 {key:'rear',wt:'rearWt',arm:'wbRearArm',moment:'wbRearMoment'},
 {key:'bag',wt:'bagWt',arm:'wbBagArm',moment:'wbBagMoment'},
 {key:'fuel',gal:'fuelGal',wt:'wbFuelWt',arm:'wbFuelArm',moment:'wbFuelMoment'},
 {key:'custom1',wt:'wbCustom1Wt',arm:'wbCustom1Arm',moment:'wbCustom1Moment'},
 {key:'custom2',wt:'wbCustom2Wt',arm:'wbCustom2Arm',moment:'wbCustom2Moment'}
];
function e(id){return ctx.el(id)}
function num(id){return ctx.nv(id)}
function factor(){return Number(e('wbMomentFormat').value)||1}
function setText(id,value){if(e(id))e(id).innerHTML=value}
function setVal(id,value,d){var node=e(id);if(!node)return;node.value=value==null||!Number.isFinite(value)?'':Number(value).toFixed(d).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}
function numeric(value){return value!==null&&value!==''&&Number.isFinite(Number(value))}
function worksheetStarted(){return rows.some(function(r){return [r.gal,r.wt,r.arm,r.moment].some(function(id){return id&&e(id).value.trim()!==''})})}
function limitsStarted(){return ['wbBasicMaxGross','wbBasicForwardCg','wbBasicAftCg','wbBagLimit','wbCustom1Limit','wbCustom2Limit'].some(function(id){return e(id).value.trim()!==''})}

function envelopePoints(profile){return ((profile&&profile.cgEnvelope)||[]).map(function(p){return {weight:Number(p.weight),forward:Number(p.forward),aft:Number(p.aft)}}).filter(function(p){return Number.isFinite(p.weight)&&Number.isFinite(p.forward)&&Number.isFinite(p.aft)&&p.forward<=p.aft}).sort(function(a,b){return a.weight-b.weight})}
function limitsAtWeight(points,weight){if(points.length<2||weight<points[0].weight||weight>points[points.length-1].weight)return null;for(var i=1;i<points.length;i++)if(weight<=points[i].weight){var low=points[i-1],high=points[i],ratio=(weight-low.weight)/(high.weight-low.weight||1);return {forward:low.forward+(high.forward-low.forward)*ratio,aft:low.aft+(high.aft-low.aft)*ratio}}return {forward:points[points.length-1].forward,aft:points[points.length-1].aft}}
export function evaluateEnvelope(profile,weight,cg){var points=envelopePoints(profile);if(points.length<2)return {code:'missing',label:'Full-envelope data missing',points:points};var limits=limitsAtWeight(points,weight);if(!limits)return {code:'outside',label:'Outside full envelope weight range',points:points};if(cg<limits.forward)return {code:'forward',label:'Outside full envelope—too far forward',points:points,limits:limits};if(cg>limits.aft)return {code:'aft',label:'Outside full envelope—too far aft',points:points,limits:limits};return {code:'inside',label:'Inside full envelope',points:points,limits:limits}}
function parseEnvelope(){var raw=e('wbEnvelopePoints').value.trim();if(!raw)return {points:[],error:null};try{var data=JSON.parse(raw);if(!Array.isArray(data))throw new Error('Envelope must be a JSON array.');var points=envelopePoints({cgEnvelope:data});if(points.length<2||points.length!==data.length)throw new Error('Enter at least two valid weight, forward, and aft boundary points.');return {points:points,error:null}}catch(error){return {points:[],error:error}}}

function legacyProfile(){var keys=['jp_aircraft','jp_aircrafts','jp_aircraftList','jp_acList'];for(var i=0;i<keys.length;i++){try{var data=JSON.parse(localStorage.getItem(keys[i])||'null'),list=Array.isArray(data)?data:(data&&Array.isArray(data.aircraft)?data.aircraft:null);if(list&&list.length){var selected=localStorage.jp_selectedAircraft||localStorage.jp_acId;return list.find(function(item){return item.id===selected||item.n===selected})||list[0]}}catch(error){console.warn('Skipped unreadable legacy aircraft data in '+keys[i])}}return null}
function migrateLegacyProfile(){if(localStorage.jp_wbStandaloneMigrated)return;var profile=legacyProfile(),map=[['wbEmptyWt','emptyWt',1],['wbEmptyArm','emptyArm',2],['wbPilotArm','frontArm',2],['wbFrontRightArm','frontArm',2],['wbRearArm','rearArm',2],['wbBagArm','bagArm',2],['wbFuelArm','fuelArm',2],['wbBasicMaxGross','maxWt',0],['wbFuelDensity','fuelPpg',1]];if(profile)map.forEach(function(pair){if(e(pair[0]).value===''&&numeric(profile[pair[1]])){setVal(pair[0],Number(profile[pair[1]]),pair[2]);localStorage['jp_'+pair[0]]=e(pair[0]).value}});localStorage.jp_wbStandaloneMigrated='1'}
function syncFuel(){var ppg=num('wbFuelDensity')||6,gallons=num('fuelGal'),weight=num('wbFuelWt');if(activeInput==='wbFuelWt'&&weight!=null){gallons=weight/ppg;setVal('fuelGal',gallons,2)}else if(gallons!=null){weight=gallons*ppg;setVal('wbFuelWt',weight,1)}else if(weight!=null){gallons=weight/ppg;setVal('fuelGal',gallons,2)}return {gallons:gallons,weight:weight}}
function rowValue(row,momentFactor){var weight=num(row.wt),arm=num(row.arm),shown=num(row.moment),moment=shown==null?null:shown*momentFactor;if(weight!=null&&arm!=null){moment=weight*arm;setVal(row.moment,moment/momentFactor,2)}else if(weight!=null&&moment!=null&&weight!==0){arm=moment/weight;setVal(row.arm,arm,2)}else if(arm!=null&&moment!=null&&arm!==0){weight=moment/arm;setVal(row.wt,weight,1)}return {weight:weight||0,moment:moment||0}}

function renderBasic(totalWeight,cg,fmt,pill){var show=worksheetStarted()&&limitsStarted();e('wbBasicResults').classList.toggle('hidden',!show);if(!show)return;var max=num('wbBasicMaxGross'),forward=num('wbBasicForwardCg'),aft=num('wbBasicAftCg');setText('wbWeightStatus',max==null?pill('Maximum gross not entered','warn'):(totalWeight<=max?pill('Within limit','good'):pill('Over limit','bad')));setText('wbCgStatus',forward==null||aft==null?pill('Forward and aft limits required','warn'):(forward>aft?pill('Invalid entered limits','bad'):(cg>=forward&&cg<=aft?pill('Within entered basic limits','good'):pill('Outside entered limits','bad'))));var checks=[['bagWt','wbBagLimit','Baggage'],['wbCustom1Wt','wbCustom1Limit','Station 1'],['wbCustom2Wt','wbCustom2Limit','Station 2']],entered=false,exceeded=[];checks.forEach(function(check){var limit=num(check[1]);if(limit!=null){entered=true;if((num(check[0])||0)>limit)exceeded.push(check[2])}});setText('wbStationStatus',!entered?pill('No station limits entered','warn'):(exceeded.length?pill('Exceeded: '+exceeded.join(', '),'bad'):pill('Pass','good')))}
function renderGraph(points,totalWeight,cg,max){var host=e('wbEnvelopeGraph');if(!points.length){host.innerHTML='';return}var arms=[],weights=[];points.forEach(function(p){arms.push(p.forward,p.aft);weights.push(p.weight)});var minA=Math.min.apply(null,arms)-1,maxA=Math.max.apply(null,arms)+1,minW=Math.max(0,Math.min.apply(null,weights)-100),maxW=Math.max.apply(null,weights)+100,w=360,h=270,l=52,r=12,t=18,b=38;function x(v){return l+(v-minA)/(maxA-minA)*(w-l-r)}function y(v){return t+(maxW-v)/(maxW-minW)*(h-t-b)}var polygon=points.map(function(p){return x(p.forward)+','+y(p.weight)}).concat(points.slice().reverse().map(function(p){return x(p.aft)+','+y(p.weight)})).join(' '),dot=totalWeight?'<circle cx="'+Math.max(l,Math.min(w-r,x(cg)))+'" cy="'+Math.max(t,Math.min(h-b,y(totalWeight)))+'" r="7" fill="#fff" stroke="#58b7ff" stroke-width="3"/>':'',gross=max?'<line x1="'+l+'" x2="'+(w-r)+'" y1="'+y(max)+'" y2="'+y(max)+'" stroke="#ff6b6b" stroke-dasharray="6 4"/>':'';host.innerHTML='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Full weight-dependent CG envelope"><polygon points="'+polygon+'" fill="#58b7ff18" stroke="#58b7ff" stroke-width="2"/>'+gross+dot+'<text x="180" y="260" fill="#f4f7fb" text-anchor="middle">CG arm (in)</text><text x="12" y="135" fill="#f4f7fb" text-anchor="middle" transform="rotate(-90 12 135)">Weight (lb)</text></svg>'}
function renderFullEnvelope(totalWeight,cg,max,pill){var parsed=parseEnvelope(),show=worksheetStarted()&&(parsed.points.length||parsed.error);e('wbFullEnvelopeResult').classList.toggle('hidden',!show);if(!show)return 'missing';if(parsed.error){setText('wbEnvelopeStatus',pill('Invalid envelope data','bad'));setText('wbEnvelopeGraph','<div class="cgPlotWarning">'+parsed.error.message+'</div>');return 'invalid'}var result=evaluateEnvelope({cgEnvelope:parsed.points},totalWeight,cg);setText('wbEnvelopeStatus',pill(result.label,result.code==='inside'?'good':'bad'));renderGraph(parsed.points,totalWeight,cg,max);return result.code}

export function calcWB(){if(!ctx)return;var fmt=ctx.fmt,pill=ctx.pill,momentFactor=factor(),fuel=syncFuel(),totalWeight=0,totalMoment=0;rows.forEach(function(row){var result=rowValue(row,momentFactor);totalWeight+=result.weight;totalMoment+=result.moment});var cg=totalWeight?totalMoment/totalWeight:0,max=num('wbBasicMaxGross'),remaining=max==null?null:max-totalWeight;setText('wbAcLabel','No aircraft profile required. Values stay on this device until Clear is selected.');setText('wbModeHint','Enter any two values in a row to calculate the third. Selected display: '+(momentFactor===1?'Moment':'Moment / '+momentFactor)+'.');setText('wbProfileWarnings','');setText('wbTotalWeightCell',totalWeight?fmt(totalWeight,1):'—');setText('wbTotalArmCell',totalWeight?fmt(cg,2):'—');setText('wbTotalMomentCell',totalWeight?fmt(totalMoment/momentFactor,2):'—');setText('wbFuelSummary',fuel.gallons!=null?fmt(fuel.gallons,1)+' gal ('+fmt(fuel.weight||0,1)+' lb)':'—');setText('wbWeight',totalWeight?fmt(totalWeight,1)+' lb':'—');setText('wbMoment',totalWeight?fmt(totalMoment/momentFactor,2):'—');setText('wbCg',totalWeight?fmt(cg,2)+' in':'—');setText('wbRemain',remaining==null?'—':fmt(remaining,1)+' lb');setText('wbMaxGross',max==null?'—':fmt(max,0)+' lb');renderBasic(totalWeight,cg,fmt,pill);var envelopeStatus=renderFullEnvelope(totalWeight,cg,max,pill);lastWbSnapshot={aircraftId:'',totalWeightLb:totalWeight||null,cgArmIn:totalWeight?cg:null,fuelGallons:fuel.gallons,fuelWeightLb:fuel.weight,envelopeStatus:envelopeStatus,calculatedAt:new Date().toISOString()};localStorage.jp_wbMomentFormat=String(momentFactor);activeInput=null}

function convertMoments(oldFactor,newFactor){rows.forEach(function(row){var shown=num(row.moment);if(shown!=null)setVal(row.moment,shown*oldFactor/newFactor,2)})}
export function initWb(context){ctx=context;e('wbMomentFormat').value=localStorage.jp_wbMomentFormat||'1';e('wbEnvelopePoints').value=localStorage.jp_wbEnvelopePoints||'';migrateLegacyProfile();e('wbMomentFormat').addEventListener('change',function(){convertMoments(Number(localStorage.jp_wbMomentFormat)||1,factor());ctx.calcAll()});rows.forEach(function(row){[row.gal,row.wt,row.arm,row.moment].filter(Boolean).forEach(function(id){e(id).addEventListener('input',function(){activeInput=id;ctx.calcAll()})})});['wbCustom1Label','wbCustom2Label','wbFuelDensity','wbBasicMaxGross','wbBasicForwardCg','wbBasicAftCg','wbBagLimit','wbCustom1Limit','wbCustom2Limit'].forEach(function(id){e(id).addEventListener('input',ctx.calcAll)});e('wbEnvelopePoints').addEventListener('input',function(){localStorage.jp_wbEnvelopePoints=e('wbEnvelopePoints').value;ctx.calcAll()});e('wbClearBtn').addEventListener('click',function(){if(!confirm('Clear all W&B worksheet values and limits saved on this device?'))return;var ids=[];rows.forEach(function(row){ids=ids.concat([row.gal,row.wt,row.arm,row.moment])});ids=ids.concat(['wbCustom1Label','wbCustom2Label','wbBasicMaxGross','wbBasicForwardCg','wbBasicAftCg','wbBagLimit','wbCustom1Limit','wbCustom2Limit','wbEnvelopePoints']);ids.filter(Boolean).forEach(function(id){e(id).value='';localStorage.removeItem('jp_'+id)});activeInput=null;ctx.calcAll()})}
