import { US_REGIONS, allSupportedZones, regionForZone } from './zulu-time-data.js';
import { convertZuluTime, currentInput } from './zulu-time-calculations.js';

var ctx=null,lastResult=null;
function e(id){return ctx.el(id)}
function option(value,label){var node=document.createElement('option');node.value=value;node.textContent=label;return node}
function fillStates(){var select=e('zuluState');select.appendChild(option('','Choose state or territory'));US_REGIONS.forEach(function(region){select.appendChild(option(region.code,region.name))})}
function fillZones(){var select=e('zuluTimezone');select.innerHTML='';allSupportedZones().forEach(function(zone){select.appendChild(option(zone,zone))})}
function fillRegions(state,preferredZone){var region=US_REGIONS.find(function(item){return item.code===state}),select=e('zuluRegion');select.innerHTML='';if(!region){select.appendChild(option('','Choose a state first'));select.disabled=true;return}region.zones.forEach(function(item){select.appendChild(option(item[1],item[0]+' — '+item[1]))});select.disabled=region.zones.length===1;if(preferredZone&&region.zones.some(function(item){return item[1]===preferredZone}))select.value=preferredZone;else select.selectedIndex=0;e('zuluTimezone').value=select.value}
function setStatus(message,bad){e('zuluStatus').textContent=message||'';e('zuluStatus').style.color=bad?'var(--r)':'var(--m)'}
function showResult(result){lastResult=result.ok?result:null;e('zuluResult').classList.toggle('hidden',!result.ok);if(!result.ok){setStatus(result.message,true);if(result.code==='ambiguous'){e('zuluOccurrenceWrap').classList.remove('hidden');var select=e('zuluOccurrence');select.innerHTML='<option value=\"\">Choose occurrence</option>';result.choices.forEach(function(item){select.appendChild(option(item.value,item.label))})}else e('zuluOccurrenceWrap').classList.add('hidden');return}setStatus('',false);e('zuluOccurrenceWrap').classList.add('hidden');e('zuluLocalDate').textContent=result.localDate;e('zuluLocalTime').textContent=result.localTime+' '+result.zoneAbbreviation;e('zuluZuluDate').textContent=result.zuluDate;e('zuluZuluTime').textContent=result.zuluTime;e('zuluZoneMeta').textContent=result.zoneAbbreviation+' • '+result.offset;var badge=e('zuluDayBadge');badge.classList.toggle('hidden',!result.dayRelation);badge.textContent=result.dayRelation==='previous'?'PREVIOUS DAY':'NEXT DAY'}
function calculate(){showResult(convertZuluTime({direction:e('zuluDirection').value,date:e('zuluDate').value,time:e('zuluTime').value,zone:e('zuluTimezone').value,occurrence:e('zuluOccurrence').value}))}
function saveSettings(){localStorage.jp_zuluDirection=e('zuluDirection').value;localStorage.jp_zuluTimezone=e('zuluTimezone').value}
function syncStateFromZone(zone){var region=regionForZone(zone);if(region){e('zuluState').value=region.code;fillRegions(region.code,zone)}else{e('zuluState').value='';fillRegions('')}}
async function copy(text){try{await navigator.clipboard.writeText(text);setStatus('Copied: '+text,false)}catch(error){setStatus('Copy was blocked by the browser. Select the result and copy it manually.',true)}}
function reset(){e('zuluDirection').value='local-to-zulu';e('zuluTimezone').value='America/Denver';syncStateFromZone('America/Denver');e('zuluDate').value='';e('zuluTime').value='';e('zuluOccurrence').value='';e('zuluOccurrenceWrap').classList.add('hidden');e('zuluResult').classList.add('hidden');lastResult=null;setStatus('',false);localStorage.removeItem('jp_zuluDirection');localStorage.removeItem('jp_zuluTimezone')}

export function initZuluTime(context){ctx=context;fillStates();fillZones();var zone=localStorage.jp_zuluTimezone||Intl.DateTimeFormat().resolvedOptions().timeZone;if(!allSupportedZones().includes(zone))zone='America/Denver';e('zuluTimezone').value=zone;e('zuluDirection').value=localStorage.jp_zuluDirection==='zulu-to-local'?'zulu-to-local':'local-to-zulu';syncStateFromZone(zone);e('zuluState').addEventListener('change',function(){fillRegions(e('zuluState').value);saveSettings()});e('zuluRegion').addEventListener('change',function(){e('zuluTimezone').value=e('zuluRegion').value;saveSettings()});e('zuluTimezone').addEventListener('change',function(){syncStateFromZone(e('zuluTimezone').value);saveSettings()});e('zuluDirection').addEventListener('change',function(){e('zuluOccurrenceWrap').classList.add('hidden');saveSettings()});e('zuluOccurrence').addEventListener('change',calculate);e('zuluCalculateBtn').addEventListener('click',calculate);e('zuluCurrentBtn').addEventListener('click',function(){var current=currentInput(e('zuluDirection').value,e('zuluTimezone').value);e('zuluDate').value=current.date;e('zuluTime').value=current.time;calculate()});e('zuluSwapBtn').addEventListener('click',function(){e('zuluDirection').value=e('zuluDirection').value==='local-to-zulu'?'zulu-to-local':'local-to-zulu';saveSettings();if(lastResult){e('zuluDate').value=(e('zuluDirection').value==='zulu-to-local'?lastResult.zuluDate:lastResult.localDate).replace(/(\d{2}) (\w{3}) (\d{4})/,function(_,d,m,y){return y+'-'+String(['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'].indexOf(m)+1).padStart(2,'0')+'-'+d});e('zuluTime').value=(e('zuluDirection').value==='zulu-to-local'?lastResult.zuluTime:lastResult.localTime).slice(0,2)+':'+(e('zuluDirection').value==='zulu-to-local'?lastResult.zuluTime:lastResult.localTime).slice(2,4);calculate()}});e('zuluCopyTimeBtn').addEventListener('click',function(){if(lastResult)copy(lastResult.zuluTime)});e('zuluCopyFullBtn').addEventListener('click',function(){if(lastResult)copy(lastResult.zuluDate+' '+lastResult.zuluTime)});e('zuluResetBtn').addEventListener('click',reset)}
